# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - development

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'timeweb_server'
    runOptions: 'commands'
    commands:
      ssh root@92.53.104.70 'bash -s' < ./deploy.sh
