version: '3.8'

networks:
  memohub-network:
    driver: bridge
services:
  aboutme.web:
    build:
      context: .
      dockerfile: AboutMe.Web/Dockerfile    
    restart: always
    ports:
      - "8080:80"
    networks:
      - memohub-network
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: MemoHubDb
      MYSQL_USER: user
      MYSQL_PASSWORD: b1234567
      MYSQL_ROOT_PASSWORD: c1234567
    ports:
      - "3306:3306"
    volumes:
      - ../var/lib/mysql:/var/lib/mysql
    networks:
      - memohub-network